# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e842d24dcdae976c990ba5100f69f9f096533f6adf8301edfe33b15e5474efffdd9e46afa1b1d0626f42317c87dc8484a558c5e9e44da53c9921eeb3d722a1

test:
  secret_key_base: b47f148fa1ec10d8d40f11dbc8991a08912d995d06988a1efc02250efab9190f7101e9b659bc5f8d0da429b7b0dec320895363176c5fc0c3e808d3c36cdd8e72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
